language: php
php:
  - 7.3

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction

script:
  - vendor/bin/phpcs src/ tests/ -n -p -s
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit
