language: php
php:
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpcs src/ tests/ -n -p -s
  - vendor/bin/phpstan analyse src tests
  - vendor/bin/phpunit
